/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	tryapi "github.com/nightfury1204/test-apiserver/pkg/apis/tryapi"
	scheme "github.com/nightfury1204/test-apiserver/pkg/client/clientset/internalversion/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PlayersGetter has a method to return a PlayerInterface.
// A group's client should implement this interface.
type PlayersGetter interface {
	Players(namespace string) PlayerInterface
}

// PlayerInterface has methods to work with Player resources.
type PlayerInterface interface {
	Create(*tryapi.Player) (*tryapi.Player, error)
	Update(*tryapi.Player) (*tryapi.Player, error)
	UpdateStatus(*tryapi.Player) (*tryapi.Player, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*tryapi.Player, error)
	List(opts v1.ListOptions) (*tryapi.PlayerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *tryapi.Player, err error)
	PlayerExpansion
}

// players implements PlayerInterface
type players struct {
	client rest.Interface
	ns     string
}

// newPlayers returns a Players
func newPlayers(c *TryapiClient, namespace string) *players {
	return &players{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the player, and returns the corresponding player object, and an error if there is any.
func (c *players) Get(name string, options v1.GetOptions) (result *tryapi.Player, err error) {
	result = &tryapi.Player{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("players").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Players that match those selectors.
func (c *players) List(opts v1.ListOptions) (result *tryapi.PlayerList, err error) {
	result = &tryapi.PlayerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("players").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested players.
func (c *players) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("players").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a player and creates it.  Returns the server's representation of the player, and an error, if there is any.
func (c *players) Create(player *tryapi.Player) (result *tryapi.Player, err error) {
	result = &tryapi.Player{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("players").
		Body(player).
		Do().
		Into(result)
	return
}

// Update takes the representation of a player and updates it. Returns the server's representation of the player, and an error, if there is any.
func (c *players) Update(player *tryapi.Player) (result *tryapi.Player, err error) {
	result = &tryapi.Player{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("players").
		Name(player.Name).
		Body(player).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *players) UpdateStatus(player *tryapi.Player) (result *tryapi.Player, err error) {
	result = &tryapi.Player{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("players").
		Name(player.Name).
		SubResource("status").
		Body(player).
		Do().
		Into(result)
	return
}

// Delete takes name of the player and deletes it. Returns an error if one occurs.
func (c *players) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("players").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *players) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("players").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched player.
func (c *players) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *tryapi.Player, err error) {
	result = &tryapi.Player{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("players").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
