// This file was automatically generated by lister-gen

package v1alpha1

// EyeListerExpansion allows custom methods to be added to
// EyeLister.
type EyeListerExpansion interface{}

// EyeNamespaceListerExpansion allows custom methods to be added to
// EyeNamespaceLister.
type EyeNamespaceListerExpansion interface{}
