// +build !ignore_autogenerated

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	tryapi "github.com/nightfury1204/test-apiserver/pkg/apis/tryapi"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Eye_To_tryapi_Eye,
		Convert_tryapi_Eye_To_v1alpha1_Eye,
		Convert_v1alpha1_EyeList_To_tryapi_EyeList,
		Convert_tryapi_EyeList_To_v1alpha1_EyeList,
		Convert_v1alpha1_EyeSpec_To_tryapi_EyeSpec,
		Convert_tryapi_EyeSpec_To_v1alpha1_EyeSpec,
		Convert_v1alpha1_EyeStatus_To_tryapi_EyeStatus,
		Convert_tryapi_EyeStatus_To_v1alpha1_EyeStatus,
		Convert_v1alpha1_EyeStatusStrategy_To_tryapi_EyeStatusStrategy,
		Convert_tryapi_EyeStatusStrategy_To_v1alpha1_EyeStatusStrategy,
		Convert_v1alpha1_EyeStrategy_To_tryapi_EyeStrategy,
		Convert_tryapi_EyeStrategy_To_v1alpha1_EyeStrategy,
	)
}

func autoConvert_v1alpha1_Eye_To_tryapi_Eye(in *Eye, out *tryapi.Eye, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_EyeSpec_To_tryapi_EyeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_EyeStatus_To_tryapi_EyeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Eye_To_tryapi_Eye is an autogenerated conversion function.
func Convert_v1alpha1_Eye_To_tryapi_Eye(in *Eye, out *tryapi.Eye, s conversion.Scope) error {
	return autoConvert_v1alpha1_Eye_To_tryapi_Eye(in, out, s)
}

func autoConvert_tryapi_Eye_To_v1alpha1_Eye(in *tryapi.Eye, out *Eye, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_tryapi_EyeSpec_To_v1alpha1_EyeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_tryapi_EyeStatus_To_v1alpha1_EyeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_tryapi_Eye_To_v1alpha1_Eye is an autogenerated conversion function.
func Convert_tryapi_Eye_To_v1alpha1_Eye(in *tryapi.Eye, out *Eye, s conversion.Scope) error {
	return autoConvert_tryapi_Eye_To_v1alpha1_Eye(in, out, s)
}

func autoConvert_v1alpha1_EyeList_To_tryapi_EyeList(in *EyeList, out *tryapi.EyeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]tryapi.Eye)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_EyeList_To_tryapi_EyeList is an autogenerated conversion function.
func Convert_v1alpha1_EyeList_To_tryapi_EyeList(in *EyeList, out *tryapi.EyeList, s conversion.Scope) error {
	return autoConvert_v1alpha1_EyeList_To_tryapi_EyeList(in, out, s)
}

func autoConvert_tryapi_EyeList_To_v1alpha1_EyeList(in *tryapi.EyeList, out *EyeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Eye)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_tryapi_EyeList_To_v1alpha1_EyeList is an autogenerated conversion function.
func Convert_tryapi_EyeList_To_v1alpha1_EyeList(in *tryapi.EyeList, out *EyeList, s conversion.Scope) error {
	return autoConvert_tryapi_EyeList_To_v1alpha1_EyeList(in, out, s)
}

func autoConvert_v1alpha1_EyeSpec_To_tryapi_EyeSpec(in *EyeSpec, out *tryapi.EyeSpec, s conversion.Scope) error {
	out.Description = in.Description
	return nil
}

// Convert_v1alpha1_EyeSpec_To_tryapi_EyeSpec is an autogenerated conversion function.
func Convert_v1alpha1_EyeSpec_To_tryapi_EyeSpec(in *EyeSpec, out *tryapi.EyeSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_EyeSpec_To_tryapi_EyeSpec(in, out, s)
}

func autoConvert_tryapi_EyeSpec_To_v1alpha1_EyeSpec(in *tryapi.EyeSpec, out *EyeSpec, s conversion.Scope) error {
	out.Description = in.Description
	return nil
}

// Convert_tryapi_EyeSpec_To_v1alpha1_EyeSpec is an autogenerated conversion function.
func Convert_tryapi_EyeSpec_To_v1alpha1_EyeSpec(in *tryapi.EyeSpec, out *EyeSpec, s conversion.Scope) error {
	return autoConvert_tryapi_EyeSpec_To_v1alpha1_EyeSpec(in, out, s)
}

func autoConvert_v1alpha1_EyeStatus_To_tryapi_EyeStatus(in *EyeStatus, out *tryapi.EyeStatus, s conversion.Scope) error {
	out.Ok = in.Ok
	return nil
}

// Convert_v1alpha1_EyeStatus_To_tryapi_EyeStatus is an autogenerated conversion function.
func Convert_v1alpha1_EyeStatus_To_tryapi_EyeStatus(in *EyeStatus, out *tryapi.EyeStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_EyeStatus_To_tryapi_EyeStatus(in, out, s)
}

func autoConvert_tryapi_EyeStatus_To_v1alpha1_EyeStatus(in *tryapi.EyeStatus, out *EyeStatus, s conversion.Scope) error {
	out.Ok = in.Ok
	return nil
}

// Convert_tryapi_EyeStatus_To_v1alpha1_EyeStatus is an autogenerated conversion function.
func Convert_tryapi_EyeStatus_To_v1alpha1_EyeStatus(in *tryapi.EyeStatus, out *EyeStatus, s conversion.Scope) error {
	return autoConvert_tryapi_EyeStatus_To_v1alpha1_EyeStatus(in, out, s)
}

func autoConvert_v1alpha1_EyeStatusStrategy_To_tryapi_EyeStatusStrategy(in *EyeStatusStrategy, out *tryapi.EyeStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_EyeStatusStrategy_To_tryapi_EyeStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_EyeStatusStrategy_To_tryapi_EyeStatusStrategy(in *EyeStatusStrategy, out *tryapi.EyeStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_EyeStatusStrategy_To_tryapi_EyeStatusStrategy(in, out, s)
}

func autoConvert_tryapi_EyeStatusStrategy_To_v1alpha1_EyeStatusStrategy(in *tryapi.EyeStatusStrategy, out *EyeStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_tryapi_EyeStatusStrategy_To_v1alpha1_EyeStatusStrategy is an autogenerated conversion function.
func Convert_tryapi_EyeStatusStrategy_To_v1alpha1_EyeStatusStrategy(in *tryapi.EyeStatusStrategy, out *EyeStatusStrategy, s conversion.Scope) error {
	return autoConvert_tryapi_EyeStatusStrategy_To_v1alpha1_EyeStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_EyeStrategy_To_tryapi_EyeStrategy(in *EyeStrategy, out *tryapi.EyeStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_EyeStrategy_To_tryapi_EyeStrategy is an autogenerated conversion function.
func Convert_v1alpha1_EyeStrategy_To_tryapi_EyeStrategy(in *EyeStrategy, out *tryapi.EyeStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_EyeStrategy_To_tryapi_EyeStrategy(in, out, s)
}

func autoConvert_tryapi_EyeStrategy_To_v1alpha1_EyeStrategy(in *tryapi.EyeStrategy, out *EyeStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_tryapi_EyeStrategy_To_v1alpha1_EyeStrategy is an autogenerated conversion function.
func Convert_tryapi_EyeStrategy_To_v1alpha1_EyeStrategy(in *tryapi.EyeStrategy, out *EyeStrategy, s conversion.Scope) error {
	return autoConvert_tryapi_EyeStrategy_To_v1alpha1_EyeStrategy(in, out, s)
}
