// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	tryapi "github.com/nightfury1204/test-apiserver/pkg/apis/tryapi"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Player_To_tryapi_Player,
		Convert_tryapi_Player_To_v1alpha1_Player,
		Convert_v1alpha1_PlayerList_To_tryapi_PlayerList,
		Convert_tryapi_PlayerList_To_v1alpha1_PlayerList,
		Convert_v1alpha1_PlayerSpec_To_tryapi_PlayerSpec,
		Convert_tryapi_PlayerSpec_To_v1alpha1_PlayerSpec,
		Convert_v1alpha1_PlayerStatus_To_tryapi_PlayerStatus,
		Convert_tryapi_PlayerStatus_To_v1alpha1_PlayerStatus,
	)
}

func autoConvert_v1alpha1_Player_To_tryapi_Player(in *Player, out *tryapi.Player, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PlayerSpec_To_tryapi_PlayerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PlayerStatus_To_tryapi_PlayerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Player_To_tryapi_Player is an autogenerated conversion function.
func Convert_v1alpha1_Player_To_tryapi_Player(in *Player, out *tryapi.Player, s conversion.Scope) error {
	return autoConvert_v1alpha1_Player_To_tryapi_Player(in, out, s)
}

func autoConvert_tryapi_Player_To_v1alpha1_Player(in *tryapi.Player, out *Player, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_tryapi_PlayerSpec_To_v1alpha1_PlayerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_tryapi_PlayerStatus_To_v1alpha1_PlayerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_tryapi_Player_To_v1alpha1_Player is an autogenerated conversion function.
func Convert_tryapi_Player_To_v1alpha1_Player(in *tryapi.Player, out *Player, s conversion.Scope) error {
	return autoConvert_tryapi_Player_To_v1alpha1_Player(in, out, s)
}

func autoConvert_v1alpha1_PlayerList_To_tryapi_PlayerList(in *PlayerList, out *tryapi.PlayerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]tryapi.Player)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PlayerList_To_tryapi_PlayerList is an autogenerated conversion function.
func Convert_v1alpha1_PlayerList_To_tryapi_PlayerList(in *PlayerList, out *tryapi.PlayerList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PlayerList_To_tryapi_PlayerList(in, out, s)
}

func autoConvert_tryapi_PlayerList_To_v1alpha1_PlayerList(in *tryapi.PlayerList, out *PlayerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Player)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_tryapi_PlayerList_To_v1alpha1_PlayerList is an autogenerated conversion function.
func Convert_tryapi_PlayerList_To_v1alpha1_PlayerList(in *tryapi.PlayerList, out *PlayerList, s conversion.Scope) error {
	return autoConvert_tryapi_PlayerList_To_v1alpha1_PlayerList(in, out, s)
}

func autoConvert_v1alpha1_PlayerSpec_To_tryapi_PlayerSpec(in *PlayerSpec, out *tryapi.PlayerSpec, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_PlayerSpec_To_tryapi_PlayerSpec is an autogenerated conversion function.
func Convert_v1alpha1_PlayerSpec_To_tryapi_PlayerSpec(in *PlayerSpec, out *tryapi.PlayerSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PlayerSpec_To_tryapi_PlayerSpec(in, out, s)
}

func autoConvert_tryapi_PlayerSpec_To_v1alpha1_PlayerSpec(in *tryapi.PlayerSpec, out *PlayerSpec, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_tryapi_PlayerSpec_To_v1alpha1_PlayerSpec is an autogenerated conversion function.
func Convert_tryapi_PlayerSpec_To_v1alpha1_PlayerSpec(in *tryapi.PlayerSpec, out *PlayerSpec, s conversion.Scope) error {
	return autoConvert_tryapi_PlayerSpec_To_v1alpha1_PlayerSpec(in, out, s)
}

func autoConvert_v1alpha1_PlayerStatus_To_tryapi_PlayerStatus(in *PlayerStatus, out *tryapi.PlayerStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_PlayerStatus_To_tryapi_PlayerStatus is an autogenerated conversion function.
func Convert_v1alpha1_PlayerStatus_To_tryapi_PlayerStatus(in *PlayerStatus, out *tryapi.PlayerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PlayerStatus_To_tryapi_PlayerStatus(in, out, s)
}

func autoConvert_tryapi_PlayerStatus_To_v1alpha1_PlayerStatus(in *tryapi.PlayerStatus, out *PlayerStatus, s conversion.Scope) error {
	return nil
}

// Convert_tryapi_PlayerStatus_To_v1alpha1_PlayerStatus is an autogenerated conversion function.
func Convert_tryapi_PlayerStatus_To_v1alpha1_PlayerStatus(in *tryapi.PlayerStatus, out *PlayerStatus, s conversion.Scope) error {
	return autoConvert_tryapi_PlayerStatus_To_v1alpha1_PlayerStatus(in, out, s)
}
