/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	tryapi "github.com/nightfury1204/test-apiserver/pkg/apis/tryapi"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePlayers implements PlayerInterface
type FakePlayers struct {
	Fake *FakeTryapi
	ns   string
}

var playersResource = schema.GroupVersionResource{Group: "tryapi.nahid.com", Version: "", Resource: "players"}

var playersKind = schema.GroupVersionKind{Group: "tryapi.nahid.com", Version: "", Kind: "Player"}

// Get takes name of the player, and returns the corresponding player object, and an error if there is any.
func (c *FakePlayers) Get(name string, options v1.GetOptions) (result *tryapi.Player, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(playersResource, c.ns, name), &tryapi.Player{})

	if obj == nil {
		return nil, err
	}
	return obj.(*tryapi.Player), err
}

// List takes label and field selectors, and returns the list of Players that match those selectors.
func (c *FakePlayers) List(opts v1.ListOptions) (result *tryapi.PlayerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(playersResource, playersKind, c.ns, opts), &tryapi.PlayerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &tryapi.PlayerList{}
	for _, item := range obj.(*tryapi.PlayerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested players.
func (c *FakePlayers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(playersResource, c.ns, opts))

}

// Create takes the representation of a player and creates it.  Returns the server's representation of the player, and an error, if there is any.
func (c *FakePlayers) Create(player *tryapi.Player) (result *tryapi.Player, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(playersResource, c.ns, player), &tryapi.Player{})

	if obj == nil {
		return nil, err
	}
	return obj.(*tryapi.Player), err
}

// Update takes the representation of a player and updates it. Returns the server's representation of the player, and an error, if there is any.
func (c *FakePlayers) Update(player *tryapi.Player) (result *tryapi.Player, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(playersResource, c.ns, player), &tryapi.Player{})

	if obj == nil {
		return nil, err
	}
	return obj.(*tryapi.Player), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePlayers) UpdateStatus(player *tryapi.Player) (*tryapi.Player, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(playersResource, "status", c.ns, player), &tryapi.Player{})

	if obj == nil {
		return nil, err
	}
	return obj.(*tryapi.Player), err
}

// Delete takes name of the player and deletes it. Returns an error if one occurs.
func (c *FakePlayers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(playersResource, c.ns, name), &tryapi.Player{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePlayers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(playersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &tryapi.PlayerList{})
	return err
}

// Patch applies the patch and returns the patched player.
func (c *FakePlayers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *tryapi.Player, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(playersResource, c.ns, name, data, subresources...), &tryapi.Player{})

	if obj == nil {
		return nil, err
	}
	return obj.(*tryapi.Player), err
}
