apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.tryapi.nahid.com
spec:
  insecureSkipTLSVerify: true
  group: tryapi.nahid.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: api
    namespace: tryapi
  version: v1alpha1
