kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tryapi-cluster-role
subjects:
- kind: ServiceAccount
  name: apiserver
  namespace: tryapi
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io