// This file was automatically generated by informer-gen

package internalversion

import (
	tryapi "github.com/nightfury1204/test-apiserver/pkg/apis/tryapi"
	internalclientset "github.com/nightfury1204/test-apiserver/pkg/client/clientset_generated/internalclientset"
	internalinterfaces "github.com/nightfury1204/test-apiserver/pkg/client/informers_generated/internalversion/internalinterfaces"
	internalversion "github.com/nightfury1204/test-apiserver/pkg/client/listers_generated/tryapi/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// EyeInformer provides access to a shared informer and lister for
// Eyes.
type EyeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.EyeLister
}

type eyeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEyeInformer constructs a new informer for Eye type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEyeInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEyeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEyeInformer constructs a new informer for Eye type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEyeInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Tryapi().Eyes(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Tryapi().Eyes(namespace).Watch(options)
			},
		},
		&tryapi.Eye{},
		resyncPeriod,
		indexers,
	)
}

func (f *eyeInformer) defaultInformer(client internalclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEyeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *eyeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&tryapi.Eye{}, f.defaultInformer)
}

func (f *eyeInformer) Lister() internalversion.EyeLister {
	return internalversion.NewEyeLister(f.Informer().GetIndexer())
}
